.gitmodules
.travis.yml
config.sh
setup.py

Use a MacPython distribution of Python to get MacOS 10.6+ compatibility.
Deploy even when there is no tag.
Remove old workarounds.

Improvements to MacOS build

---

friture/analyzer.py
friture/plotting/glCanvasWidget.py
friture/spectrumPlotWidget.py
friture/timeplot.py
requirements.txt

Use OpenGL 3.2 Core profile on MacOS to get more compatibility. OpenGL 2.1 leads to rendering issues there (see https://github.com/raysan5/raylib/issues/341 for example)

Use OpenGL 3.2 Core profile on MacOS

---

installer/friture-setup.nsi
winbuild.ps1

This version is supposed to have no msvcr*.dll dependency and it should also not corrupt python35.dll signature

Use a recent pyinstaller (unreleased)

---

friture/audiobackend.py
friture/generator.py

The error handling when selecting an input for the generator was not correctly updated since the move to sounddevice. This fixes it, and ensures that the root cause of an error is displayed.

Fix error handling in generator

---

appveyor.yml
winbuild.ps1

To package Friture for Windows using DesktopAppConverter, the input is the output of pyinstaller. Here we add this output as a zip file. Previously only the NSIS installer was published as an artifact. This will make it easier to publish the new versions to the Windows store.

Appveyor artifacts: add a zip archive of pyinstaller output

---

.travis/install.sh
friture/__init__.py
requirements.txt
scripts/friture
setup.py

This addresses #99 by fixing how dependencies are retrieved by `python setup.py install`, and consequently by `pip install friture`.
With these fixes, the above commands will first install Cython and Numpy (since they are needed to build the extensions), then install Friture itself, then install all of its dependencies (Numpy again, PyOpenGL, PyQt5, etc.).
Tested in Ubuntu 14.04.

Fix pip install, now properly installs dependencies

---

.travis/install.sh
setup.py

This aims at solving a numpy incompatibility with AppImages built on Travis. There seems to be an incompatibility between the Travis system Python (1.15) and the one we were requiring (1.13.3), resulting in runtime fatal errors.

Upgrade numpy to 1.16.1

---

friture/analyzer.py
friture/audiobackend.py
friture/imageplot.py

Friture has issues keeping up with audio input, which tends to produce overflows, that appear as glitches in the audio signal.
This has largely been unnoticed for years because Windows MME is very forgiveable in that regard. But Windows Directsound, for example, is much more sensitive. Similarly, Alsa or PulseAudio in Linux also show a lot of glitches (even if PortAudio might not report any overflow).
Here this is fixed by taking advantage of python-rtmixer, a library that sits on top of python-sounddevice (the PortAudio wrapper). Python-rtmixer provides an audio callback that is implemented in C and doesn’t invoke the Python interpreter, therefore avoiding waiting for things like garbage collection and the GIL.
Reference: https://python-rtmixer.readthedocs.io/en/0.1.0/index.html
The …

Use python-rtmixer for low-latency audio recording

---

.travis.yml
.travis/install.sh
INSTALL.md
appimage/friture.yml

Friture AppImage is built so far with Ubuntu 14.04 LTS. The next LTS of Ubuntu is 16.04, which is already 6 years old. We can surely upgrade safely to that version as the minimum required version to run Friture.

(Travis Linux) Build with Ubuntu 16.04

---

friture/audioproc.py

Somehow I wasn't able to start friture anymore. I'm not sure what changed since it last worked, i don't use friture that regularly.
I am not sure whats going on exactly. Although the [linspace-documention](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) mentions integers, there are actually floats (2.0, is this a float in python?) in the examples.
Anyway, fixing the division (which returns a float) to a floor division (which returns an int) fixed the issue for me.
I'm on manjaro using [friture-git](https://aur.archlinux.org/packages/friture-git/)
```
~ >>> friture                                                                                                                        
2020-02-01 22:41:53,022 INFO friture.analyzer: Friture 0.41 starting on Linux …
```

Use floor division to get integer values

---

friture/audioproc.py

Addresses #132. When the FFT spectrum is cropped by lowering the max frequency, the signal was decimated N times by taking one sample every N samples. This is not correct, produces many artifacts. To keep decimation, we would need to use a proper low-pass filter (as implemented for the octave spectum for example), but it does not really seem worth it. We will just apply the FFT on top of the undecimated signal.

Remove incorrect decimation in FFT spectrum

---

friture/longlevels.py
friture/longlevels_settings.py

Fix for Fixes #143.  I decided to normalize the time units with the 2D Spectrogram and standardize on seconds, as opposed to the original minutes, for the long-time level.

Added time range and response time to long-levels

---

.github/workflows/build.yml
.github/workflows/install-linux.sh
.github/workflows/install-macos.sh
INSTALL.md
choco/packages.config
friture.spec
winbuild.ps1

Support for Macos Big Sur was only added in Python 3.9.1.
This is a first of the fixes for #154.
Also update to latest pyinstaller.

Update automated builds to Python 3.9.1

---

friture.spec

According to https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos, an app must declare why it needs microphone access.
If the appropriate key is not present in the Info.plist file when the app requests authorization or attempts to use a capture device, the system terminates the app.
Related to #154

Macos bundle: define  NSMicrophoneUsageDescription

---

.github/workflows/install-macos.sh
friture.spec
installer/pyinstaller-hooks/hook-sounddevice.py

For Macos Big Sur, the stable portaudio (19.6.0) makes Friture freeze on startup.
So we install from latest master instead, and we tell pyinstaller to bundle that version instead of the version provided by python-sounddevice.
See #154
Also remove the vcruntime140.dll workaround that is not needed with latest pyinstaller, and was getting confusing to apply next to the Macos setting.

Macos builds: install latest portaudio

---

appimage/friture.yml

The portaudio library is missing from the Linux appimage, requiring users to install portaudio manually, which is not the original intent.
Fixes #108 and #145

Linux AppImage: add portaudio

---

.gitignore
friture/plotting/glCanvasWidget.py
friture/plotting/quadsItem.py
friture/timeplot.py
sandbox/2dpainting.py
sandbox/hellogl.py

Improvement to address #170
Catching PyOpenGL import errors might hide a bigger problem. The packages that we build are meant to include it anyway, so it's better to get the original full error.
That piece of code was a leftover from the PyOpenGL samples that were used originally.

Do not catch PyOpenGL import errors

---

friture/analyzer.py

Addressing issue #92. When removing all docks and closing the application, i found the following value in my Friture.conf
```
[Docks]
Dock%201\timeRange=50
Dock%201\type=1
dockNames=@Invalid()
```
While i did not find a way to prevent the invalid value in the config file, i did find a way to handle the invalid one upon starting the application.
Tested on a linux system

Fix starting application without any docks

---

setup.py

There is an ABI compatibility issue on some platforms involving the interaction between the Cython-generated shared object files included in the OpenGL-accelerate 3.1.5 and numpy 1.19.3 PyPI packages which can cause a missing symbol error during import.
This causes friture to throw an exception On MacOS Big Sur and Windows during startup.
Fixes two reports of the issue here:  https://github.com/tlecomte/friture/issues/177
And (probably) this one without the logs also:  https://github.com/tlecomte/friture/issues/170.
(I see the same symptom when I try to install the downloadable fricture dmg file on Big Sur)
I don't have a full understanding of the underlying issue, or a full list of which platforms it affects, but I can confirm from my testing on Big Sur that updating the requirements to …

Update numpy requirement from 1.19.3 to 1.20.3

---

.github/workflows/install-linux.sh
.github/workflows/install-macos.sh
winbuild.ps1

This may help for MacOS packages, since there has been a couple of improvements in that area.

chore: update to PyInstaller 4.4

---

friture/imageplot.py
friture/plotting/scaleBar.py

Fixes #191 by removing the borders around the frequency scale. Additionally, a check to avoid text being drawn beyond the widget area is implemented in `scaleBar.py`.

Fix spectrogram frequency scale by removing borders

---

MANIFEST.in
setup.py

This PR includes a couple of additional files from the QML changes in the Python package generated by setuptools. The fact that they were missing caused problem's with the packaging mechanism of my Linux distro (NixOS) as it is based on running `python setup.py install`, and will likely also cause issues with other distros such as with [the friture AUR package from Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=friture).

Include additional files in setuptools package

---

friture/levels.py
friture/plotting/coordinateTransform.py
friture/plotting/scaleBar.py
friture/plotting/titleWidget.py
friture/spectrogram_image.py
friture/spectrogram_settings.py
setup.py

Continuation of pull request #207, which failed to update on my new commit for some reason??
- In Python 3.10, the Numpy C extensions refuse to build; this is fixed by setting the dependency to numpy>=1.21.
- Implicit conversions to int are deprecated and enforced, as of Python 2.10. I think I have removed all implicit conversions from float to int, but I might've missed some, or done something in the wrong way. Review would be appreciated.
Fixes #204.
Fixes #206.

python3.10: numpy update and explicit int() #207 

---

friture/spectrum_settings.py

This PR brings spectrum_settings.py in line with spectrogram_settings.py and ensures that an int is passed to setMaximum(), fixing the TypeError exception from #212

Fix TypeError in spectrum_settings.py #212

---

.github/workflows/install-macos.sh
.gitignore
installer/fix_app_qt_folder_names_for_codesign.py

PyInstaller will try to codesign friture.app, but will fail because of the Qt5 file structure (this is visible in the build logs).
See https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt
So we fix the folder names and then sign again manually.

fix(macos): codesign despite Qt5 folder names

---

.github/workflows/install-linux.sh
appimage/friture.yml

Apply a collection of fixes to make the AppImage work correctly:
-  build PortAudio 19.7.0 from scratch to get the fixes from https://github.com/PortAudio/portaudio/pull/504, and adjust LD_LIBRARY_PATH so that it can be loaded (fix #200)
- pre-install 2 Qt5 dependencies (xcv-xinerama and xkbcommon-x11) so that PyInstaller can correctly include them in the bundle
- update to Ubuntu bionic as the base distribution

fix(AppImage): build PortAudio 19.7.0 and fix Qt5 dependencies

---

.github/workflows/install-linux.sh
.github/workflows/install-macos.sh
installer/pyinstaller-hooks/hook-sounddevice.py
setup.py
winbuild.ps1

Update various packages, including:
- pyinstaller
- pyqt5
- numpy

chore: package updates

---

.github/workflows/build.yml

Ubuntu 18 and Macos 10 runners are obsolete

chore: update Github runners

---

friture/spectrum_settings.py

This tab was introduced by #252 and causing me build errors. This patch simply replaces the tab with spaces.

remove stray tab in spectrum_settings.py which was causing a TabError

---

friture/Spectrum.qml
friture/spectrum.py
friture/spectrumPlotWidget.py
friture/spectrum_data.py
friture/spectrum_settings.py

This uses a simple 3-Harmonic Product Spectrum. It works well when tested on my own voice (whereas Fmax often makes an octave error with the first overtone).

Add an option to show estimated pitch on the spectrum.

---

friture/histplot.py
friture/imageplot.py
friture/plotting/frequency_scales.py
friture/spectrum.py
friture/spectrumPlotWidget.py

This also incorporates a new frequency scale that places major ticks at the octaves of A (standard A440 tuning), and minor ticks at the intermediate minor thirds, which is quite useful when looking at plots from a pitch perspective.
I wanted to include Alexis's parallel work for contribution credit, although it does kinda make this more complicated of a change than necessary and they added a bunch of noise by (probably automatically and unintentionally) running a code formatter on spectrumPlotWidget.py :woman_shrugging:

Show note names in pitch estimate and trackers

---

winbuild.ps1

Without this setting, the msi accepts being installed on a 32 bit Windows 10, but Friture fails to run. This closes https://github.com/tlecomte/friture/issues/264

fix(ci): msi package is x64 only

---

friture/PitchView.qml
friture/PlotArea.qml
friture/PlotGrid.qml
friture/axis.py
friture/histplot.py
friture/pitch_tracker.py
friture/pitch_tracker_settings.py
friture/spectrumPlotWidget.py

- adds a display of the current pitch and note to the right of the graph, which is nice for controlling pitch in real time. At this point #234 seems quite fully satisfied.
- shows minor grid lines in the frequency axis, instead of time, since that's usually what one wants more precision for in this graph
- replaces minimum SNR with minimum amplitude, which is kinda crude and needs tweaking to each environment, but once tweaked generally does a good job of avoiding detecting pitches in background noise (including pitched background sounds).

Make some improvements to the pitch tracker widget

---

friture/generators/pink.py
friture/plotCurve.py
friture_extensions/lfilter.pyx
friture_extensions/linear_interp.pyx
friture_extensions/lookup_table.pyx
pyproject.toml
sandbox/output.py
sandbox/pink2.py

Numpy 2 has a couple of breaking changes. The adjustments here have been tested manually, in addition to having 'pip install .' working well (to test compiling Cython extensions).
Fixes #280

chore: migrate to Numpy 2

---

.github/workflows/install-linux.sh
.github/workflows/install-macos.sh
.github/workflows/install-windows.ps1
friture.spec

PyInstaller 5.12+ should fix an error with Python 3.11.4+, so we upgrade to latest.
See https://github.com/pyinstaller/pyinstaller/pull/7694
Apply some packaging fixes:
- the playback control dll needed to be added in pyinstaller data files, since it's not in the root folder
- fix a path for Macos following a breaking change in the app structure with PyInstaller 6.0+
- remove icu dll on windows, it's apparently not included anymore

chore(deps): update PyInstaller + packaging fixes

---

friture/dock.py
friture/dockmanager.py

Overall, the intent is to make it more convenient to switch back and forth between widgets, or to temporarily show and then hide a widget, by not reverting widgets to default settings when doing this. More specifically:
- when a dock is closed, and then a new dock is created, the new dock will have the same widget with the same settings as previously (and this works on a stack if multiple docks are closed)
- when a dock is switched from one widget to another and then back, the initial settings will be preserved
- the above state is persisted in application settings

Retain widget settings through switches and closes

---

friture/FrequencyTracker.qml
friture/HistPlot.qml
friture/HorizontalScale.qml
friture/Legend.qml
friture/Levels.qml
friture/LevelsMeter.qml
friture/MeterScale.qml
friture/PitchView.qml
friture/Plot.qml
friture/PlotArea.qml
friture/PlotBackground.qml
friture/PlotGrid.qml
friture/VerticalScale.qml
friture/plotting/canvasWidget.py
friture/statisticswidget.py
pyproject.toml

Instead of hard-coding colors, we refer the system palette. This allows to support dark themes, and even switch dynamically while Friture is running.

feat(ui): use palette colors to support dark theme

---

.github/workflows/install-macos.sh

hdiutil is sometimes failing with a "Resource Busy" error. According to https://github.com/actions/runner-images/issues/7522 this is due to XProtectBehaviorService and the easiest solutions are either to kill this service or retry. Here we retry.

fix(build): retry hdiutil call

---

friture/Levels.qml

The level values are moving left to right as the digits take more or less space in the default font. To stabilize these labels, we use a monospace font by switching to Markdown formatting.

feat(levels): move values to monospace font

---

.github/workflows/build.yml
.github/workflows/install-linux.sh

Ubuntu 20.04 runners are deprecated.
Ubuntu 22.04 does not have fuse installed, and it's required for appimage builds.

chore(ci): update to ubuntu 22.04

---

friture/analyzer.py

Linux systems using Pipewire ALSA now identifies Friture when listing audio streams as described in #255 
Old:
New:

Friture now indentifies itself to Pipewire ALSA

---

friture/Levels.qml

Changed the text format from MarkdownText to StyledText and removed the inline code formatting. This fixes font size calculation and keeps the text styling and line break.

Fixed levels widget styling

---

friture/Levels.qml
friture/levels.py

https://github.com/tlecomte/friture/pull/338 changed to a 'monospace' font to fix the formatting of the levels. However, 'monospace' does not work on all platforms. On Windows, it falls back to Arial, which is not monospace.
The common workaround is to find the fixed font with Qt, and then pass it as a QML variable.
cc @Robin-K-Lynn

fix(levels): use a monospace font that works on all platforms

---

friture/FritureMainWindow.qml
friture/analyzer.py
friture/settings.py

Fixes #371
The references to the previous QWidget actions were missed when converting the toolbar to a viewmodel and QML.

fix: use viewmodel when toggling recording state when changing audio input settings

---

friture/FritureMainWindow.qml
friture/analyzer.py

os.envion[] assignments now have a check before them so they are disabled automatically if the system/user has already set a default or an override.
I added `icon.color: undefined` as all themes other than Fusion treat icon sources as a colour mask if this parameter is not set. Please test this to see if it breaks anything on other OSes. Another way of keeping the colours would be to wrap the images in an Image{}.
Running the command `QT_QUICK_CONTROLS_STYLE="Universal" ./main.py` for example changes the style to "Universal"

Environmental changes are now optional

---

friture/spectrogram_image.py

Sometimes the screen width can be returned as zero, and this can in turn cause issues creating pixmaps. Make sure the width is always at least 1.

fix(spectrogram): prevent errors for zero width

---

friture/FritureMainWindow.qml

Setting `icon.color: undefined` leads to this error: `FritureMainWindow.qml:31:21: Unable to assign [undefined] to QColor`

fix: remove icon.color: undefined
